# Generated by beam_build 
#
# You may change the list of sources used to build this accelerator
# by adjusting the list of source files below
#
SOURCES = $(EGS_SOURCEDIR)egsnrc.macros \
          $(EGS_UTILS)timing.macros \
          $(MACHINE_MACROS) $(RANDOM).macros \
          $(EGS_SOURCEDIR)transportp.macros \
          $(EGS_SOURCEDIR)pegs4_macros.mortran \
          $(BEAM_HOME)beamnrc_user_macros.mortran \
          $(EGS_UTILS)phsp_macros.mortran $(IAEA_PHSP_MACROS)\
          $(BEAM_CODE)_macros.mortran \
          $(BEAM_HOME)beam_main.mortran\
          $(BEAM_HOME)beamnrc.mortran \
          $(EGS_UTILS)xvgrplot.mortran \
          $(BEAM_CODE)_cm.mortran \
          $(EGS_SOURCEDIR)egs_utilities.mortran \
          $(EGS_SOURCEDIR)get_inputs.mortran \
          $(EGS_SOURCEDIR)get_media_inputs.mortran \
          $(RANDOM).mortran \
          $(EGS_UTILS)nrcaux.mortran \
          $(MACHINE_MORTRAN) \
          $(EGS_SOURCEDIR)egs_parallel.mortran \
          $(EGS_SOURCEDIR)pegs4_routines.mortran \
          $(EGS_SOURCEDIR)egsnrc.mortran

LIB_SOURCES = $(BEAM_HOME)beam_lib.macros \
          $(EGS_SOURCEDIR)egsnrc.macros \
          $(EGS_UTILS)timing.macros \
          $(MACHINE_MACROS) $(RANDOM).macros \
          $(EGS_SOURCEDIR)transportp.macros \
          $(EGS_SOURCEDIR)pegs4_macros.mortran \
          $(BEAM_HOME)beamnrc_user_macros.mortran \
          $(EGS_UTILS)phsp_macros.mortran $(IAEA_PHSP_MACROS)\
          $(BEAM_CODE)_macros.mortran \
          $(BEAM_HOME)beam_lib.mortran\
          $(BEAM_HOME)beamnrc.mortran \
          $(EGS_SOURCEDIR)egs_utilities.mortran \
          $(BEAM_CODE)_cm.mortran \
          $(EGS_SOURCEDIR)get_inputs.mortran \
          $(EGS_SOURCEDIR)get_media_inputs.mortran \
          $(RANDOM).mortran \
          $(EGS_UTILS)nrcaux.mortran \
          $(MACHINE_MORTRAN) \
          $(EGS_SOURCEDIR)egs_parallel.mortran \
          $(EGS_SOURCEDIR)pegs4_routines.mortran \
          $(EGS_SOURCEDIR)egsnrc.mortran
