#  modules.make file for BEAM_EXphantom
#
# Automatically generated by beam_build.exe
# Do not edit this file, all changes will be lost!
#

CM_MACRO_FILES = \
      $(CM_HOME)CHAMBER_macros.mortran

CM_MORTRAN_FILES = \
      $(CM_HOME)CHAMBER_cm.mortran
