#  modules.make file for BEAM_EX10MeVe
#
# Automatically generated by beam_build.exe
# Do not edit this file, all changes will be lost!
#

CM_MACRO_FILES = \
      $(CM_HOME)SLABS_macros.mortran\
      $(CM_HOME)CONS3R_macros.mortran\
      $(CM_HOME)CONESTAK_macros.mortran\
      $(CM_HOME)CHAMBER_macros.mortran\
      $(CM_HOME)CONESTAK_macros.mortran\
      $(CM_HOME)MIRROR_macros.mortran\
      $(CM_HOME)JAWS_macros.mortran\
      $(CM_HOME)APPLICAT_macros.mortran

CM_MORTRAN_FILES = \
      $(CM_HOME)SLABS_cm.mortran\
      $(CM_HOME)CONS3R_cm.mortran\
      $(CM_HOME)CONESTAK_cm.mortran\
      $(CM_HOME)CHAMBER_cm.mortran\
      $(CM_HOME)CONESTAK_cm.mortran\
      $(CM_HOME)MIRROR_cm.mortran\
      $(CM_HOME)JAWS_cm.mortran\
      $(CM_HOME)APPLICAT_cm.mortran
