#  modules.make file for BEAM_malli
#
# Automatically generated by beam_build.exe
# Do not edit this file, all changes will be lost!
#

CM_MACRO_FILES = \
      $(CM_HOME)SLABS_macros.mortran\
      $(CM_HOME)FLATFILT_macros.mortran\
      $(CM_HOME)CHAMBER_macros.mortran\
      $(CM_HOME)MIRROR_macros.mortran\
      $(CM_HOME)JAWS_macros.mortran

CM_MORTRAN_FILES = \
      $(CM_HOME)SLABS_cm.mortran\
      $(CM_HOME)FLATFILT_cm.mortran\
      $(CM_HOME)CHAMBER_cm.mortran\
      $(CM_HOME)MIRROR_cm.mortran\
      $(CM_HOME)JAWS_cm.mortran
